### PR TITLE
feat: add poetry as dependency manager

### PR DESCRIPTION
**Pull request by sergerdn**
Hello. I would like to add poetry as dependency manager. I believe  that `poetry` is very modern and smartest way for it. Please review  my changes. Any suggestions will be  appreciated.

**Changes:**
* feat: add poetry as dependency manager and remove requirements.txt
* feat: update and format README.md
* feat: run some tests only on supporting platform(Windows)
* feat: add Makefile(for tests only)
* add example of updated BAS project to git(BAS version 25.1.2)

Also I have a plan to make changes for run tests with different supported versions of python. 
I would like to make that feature with different pull request, is it okay for you?

### CODE REVIEW

**Comment by CheshireCaat** [comment]
Good day. Thanks for PR! I'll review all the changes over the weekend. There is one important question:

- After adding `poetry` the old way (installing via `pip`) won't work? Then it's better to leave `requrements` for backwards compatibility. It would be nice if the user saw a deprecation warning when installing with the old way, but I'm not sure if it's easy to implement.

Also need to check whether everything works correctly with earlier versions of python - 3.7 and 3.8.

> I would like to make that feature with different pull request, is it okay for you?

Yes, of course. You can also split this PR into parts - make a separate one for tests.

**Comment by sergerdn** [comment]
> * After adding `poetry` the old way (installing via `pip`) won't work? Then it's better to leave `requrements` for backwards compatibility. It would be nice if the user saw a deprecation warning when installing with the old way, but I'm not sure if it's easy to implement.

Agree with you.  I'v added an example how to export dependency to the `requirements.txt` to the docs and `Makefile`.

> Also need to check whether everything works correctly with earlier versions of python - 3.7 and 3.8.

I will add tests via `tox` into separate PR with suggested versions of python.

**Comment by sergerdn** [comment]
So, which versions of python do you suggest  for me for tests?
3.7-3.10?

**Comment by CheshireCaat** [comment]
Yes. The main thing here is to check that the installation via poetry works correctly everywhere.

**Comment by sergerdn** [comment]
> Yes. The main thing here is to check that the installation via poetry works correctly everywhere.

Okay:
- I will add run tests with different versions of python(via tox)
- I will check that installations of dependency working as expected with that versions of python(via tox)
- I will check that an example working as expected with that versions of python. I have a premium BAS subscription, it will be not a problem for me.

I will make it in a different PR. I think it will be better, but I working on it now.

**Comment by sergerdn** [comment]
I'v restored `requirements.txt`. May I ask you merge this changes "as is"? I'v prepared for you another big PR and it will be speed up my workflow.
There are only cosmetic changes, I think.

**Comment by CheshireCaat** [comment]
Left a few comments. Please move the formatting change in the `README` file to a separate PR, keep only new lines. As well as adding a script with an example.

**Comment by sergerdn** [comment]
> Left a few comments. Please move the formatting change in the `README` file to a separate PR, keep only new lines. As well as adding a script with an example.

I'v restored `README.md` before my changes. I will add any changes into separate PR. I think it is better, is it okay for you? E.g. by adding new file `CONTRIBUTING.md` or something else.

**Comment by CheshireCaat** [comment]
> > Left a few comments. Please move the formatting change in the `README` file to a separate PR, keep only new lines. As well as adding a script with an example.
> 
> I'v restored `README.md` before my changes. I will add any changes into separate PR. I think it is better, is it okay for you? E.g. by adding new file `CONTRIBUTING.md` or something else.

Yes, it's OK

**Pull request closed without merging**
